### ISSUE TITLE
CFG-LOCK疑问

### ISSUE THREAD

**Issue by jsnow0613** [wvq/onda-h410sd4-itx-hackintosh-OC#1]
你好，我安装了官网最新的bios驱动后，依旧没找到CFG-LOCK选项，请问你是在哪个菜单下看到的，谢谢

**Comment by jsnow0613** [comment]
已经找到了

**Comment by wvq** [comment]
报歉，不咋上github，才看到消息，路径是:
Advanced -> Power & Performance -> CPU -> CPU Lock Configuration -> CFG Lock
